### ISSUE TITLE
Can't boot from SD

### ISSUE THREAD

**Issue by KEALHOVIK** [manjaro-arm/radxa-zero-images#2]
I added u-boot that allows this board to boot from sd card following this instructions https://forum.radxa.com/t/introduce-the-radxa-zero/6550/111. Board started to boot, but it always hangs with the error of ERROR: device PARTUUID=... not found. Skipping fsck. I tried to change PARTUUID in /BOOT_MNJRO/extlinux/extlinux.conf to that of my BOOT_MNJRO and ROOT_MNJRO, but it still doesn't find it.
How do i boot from SD?

**Comment by KEALHOVIK** [comment]
Sorry, i managet to get further by actually providing PARTUUID of ROOT_MNJRO and not UUID, or setting UUID in config instead of PARTUUID.
But then i get:
systemd[1]: Failed to start Remount Root and Kernel File Systems.

There's also gpu error of no regulator (mali) found: -19
and it can't get RAM size

**Comment by chewitt** [comment]
Use mainline u-boot soure instead of the vendor one, see: https://github.com/chewitt/u-boot/commits/amlogic-2021.07

Precompiled (signed) binary is here https://chewitt.libreelec.tv/testing/u-boot/u-boot.bin.sd.bin-radxa-zero

The mali warning is harmless and can be ignored.

**Comment by Strit** [comment]
> Use mainline u-boot soure instead of the vendor one, see: https://github.com/chewitt/u-boot/commits/amlogic-2021.07

Does this compile and sign on an aarch64 device, or would we still need to hack together a x86_64 build environment to sign it?

**Comment by chewitt** [comment]
You can compile the u-boot source on any arch but the Amlogic signing binaries, e.g. https://github.com/LibreELEC/amlogic-boot-fip/blob/master/radxa-zero/aml_encrypt_g12a are pre-compiled for x86_64 only - not a problem for me as I always cross-compile images. If you need to compile on aarch64 use https://github.com/repk/gxlimg which (despite the GXL name) can also sign for G12A hardware; I'm not sure about G12B.

**Comment by Strit** [comment]
Thanks. Didn't know about gxlimg.

I only knew about https://github.com/angerman/meson64-tools which I was unsuccesful in using.

Will look into it when I have some time.

**Comment by chewitt** [comment]
I've not used that one (or meson-tools that it's based upon) so can't comment. The author of gxlimg "repk" can normally be found lurking in the #linux-amlogic IRC channel on Libera if you need to chat about the tool.

**Comment by KEALHOVIK** [comment]
> Use mainline u-boot soure instead of the vendor one, see: https://github.com/chewitt/u-boot/commits/amlogic-2021.07
> 
> Precompiled (signed) binary is here https://chewitt.libreelec.tv/testing/u-boot/u-boot.bin.sd.bin-radxa-zero
> 
> The mali warning is harmless and can be ignored.

I used that precompiled binary and nothing had changed, still getting the same error

**Comment by KEALHOVIK** [comment]
Using u-boot provided here and changing PARTUUIDs in /BOOT_MNJRO/extlinux/extlinux.conf and /ROOT_MNJRO/etc/fstab to those that are shown by blkid (running on actual board) helps

**Comment by Strit** [comment]
> I've not used that one (or meson-tools that it's based upon) so can't comment. The author of gxlimg "repk" can normally be found lurking in the #linux-amlogic IRC channel on Libera if you need to chat about the tool.

@chewitt Now that I've got you here, do you guys do anything special to boot kernel 5.10+ with mainline uboot on Odroids?
As mainline uboot does not support boot.ini scripts, I can't set the `loadaddr` that's needed. How do you guys get around that?

**Comment by chewitt** [comment]
Create a uImage kernel then wrap with u-boot mkimage, see the section of build-script here: https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/linux/package.mk#L193. This can be loaded from a normal extlinux.conf without needing the vendor kernel boot.ini rubbish.
